name: Feature Request
description: Sugira uma funcionalidade
title: "[FEATURE] "
labels: ["feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problema
      description: Qual problema essa feature resolve?
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solução proposta
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternativas consideradas